// src/components/StudentCheckIn.jsx
import React, { useState } from 'react';
import { Camera, CheckCircle, XCircle, QrCode } from 'lucide-react';
import api from '../services/api'; 
import '../styles/StudentCheckIn.css';

// This component simulates the QR scanning process and sends data to the backend

const StudentCheckIn = () => {
    const [scannedData, setScannedData] = useState('');
    const [status, setStatus] = useState({ message: '', type: null }); // type: 'success' | 'error'
    const [isSubmitting, setIsSubmitting] = useState(false);
    
    // Function to handle the check-in submission
    const handleCheckIn = async (e) => {
        e.preventDefault();
        setStatus({ message: '', type: null });
        
        if (!scannedData) {
            setStatus({ message: 'Please paste the scanned QR code data.', type: 'error' });
            return;
        }

        setIsSubmitting(true);
        
        try {
            // The QR code data generated by the admin contains a JSON string: 
            // {eventId: 123, data: "SECRET_TOKEN"}
            const parsedData = JSON.parse(scannedData);
            
            if (!parsedData.eventId || !parsedData.data) {
                setStatus({ message: 'Invalid QR data format.', type: 'error' });
                setIsSubmitting(false);
                return;
            }

            // Call the secure attendance check-in endpoint
            const response = await api.post('/attendance/checkin', {
                eventId: parsedData.eventId,
                scannedToken: parsedData.data, // The secret token generated by the admin
            });
            
            setStatus({ message: response.data.message || 'Attendance recorded successfully!', type: 'success' });
            setScannedData(''); // Clear the input field

        } catch (err) {
            const errorMessage = err.response?.data?.error || 'Check-in failed due to server error.';
            setStatus({ message: errorMessage, type: 'error' });
            console.error("Check-in error:", err);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="checkin-box">
            <h2 className="checkin-header"><QrCode size={24} /> Event Attendance Check-in</h2>
            <p className="checkin-instruction">Scan the QR code displayed by the event organizer.</p>

            {/* Simulated Scanning Area */}
            <div className="scanner-placeholder">
                <Camera size={48} />
                <p>
                    **Camera Scanner Placeholder** <br />
                    (In development, please paste the raw QR code data below.)
                </p>
            </div>
            
            <form onSubmit={handleCheckIn} className="checkin-form">
                <div className="input-group">
                    <label htmlFor="qrData">Paste QR Code Data Here:</label>
                    <input
                        type="text"
                        id="qrData"
                        value={scannedData}
                        onChange={(e) => setScannedData(e.target.value)}
                        placeholder='e.g., {"eventId":1,"data":"b12c5f..."}'
                        required
                    />
                </div>
                
                {status.message && (
                    <div className={`status-message status-${status.type}`}>
                        {status.type === 'success' ? <CheckCircle size={18} /> : <XCircle size={18} />}
                        {status.message}
                    </div>
                )}
                
                <button 
                    type="submit" 
                    className="btn-checkin"
                    disabled={isSubmitting}
                >
                    {isSubmitting ? 'Verifying...' : 'Submit Attendance'}
                </button>
            </form>
        </div>
    );
};

export default StudentCheckIn;